runtime: go
api_version: go1

handlers:
- url: /parts/js/(.+\.js)$
  static_files: parts/js/\1
  upload: parts/js/(.+\.js)$
  application_readable: true

- url: /parts/css/(.+\.css)$
  static_files: parts/css/\1
  upload: parts/css/(.+\.css)$
  application_readable: true

- url: /.*
  script: _go_app


# release command
# $ gcloud app browse
# $ gcloud app deploy

# $ gcloud info
# $ gcloud config set project myprofile-190812 
# $ gcloud config set project mangacreator-168316